SEARCH_DIR("/usr/lib/x86_64-linux-gnu/")
SEARCH_DIR("/lib64/")
SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib64/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/lib/gcc/x86_64-linux-gnu/10/")
SEARCH_DIR("/home/fred/bgrabitmap-11.4/bgrabitmap/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/kernel/linux/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/report/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/fpccompatibility/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/graphics/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/pascalscript/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/math/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/audio/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/db/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/image/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/unicode/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/dialogx/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/mzeoslib/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/serialcomm/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/regcomponents/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/i18n/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/kernel/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/crypto/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/assistive/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/widgets/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/opengl/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/designutils/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/editwidgets/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/dialogs/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/ifi/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/printer/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/container/")
SEARCH_DIR("/home/fred/mseide-msegui/lib/common/sysutils/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/httpd22/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-sdo/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pcap/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-json/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libpng/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pthreads/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libffi/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/opengles/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/imlib/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/openssl/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/a52/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libvlc/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/tcl/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libenet/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/gnome1/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/gnutls/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-res/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-pdf/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-extra/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/svgalib/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/odata/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/symbolic/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/webidl/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-sound/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/proj4/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-db/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pxlib/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/oggvorbis/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/tplylib/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/imagemagick/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/openal/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/mad/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/ptc/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/cairo/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libmicrohttpd/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/vcl-compat/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/graph/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fpgtk/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libgc/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/gdbm/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/oracle/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/ldap/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/httpd24/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/gtk1/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/opengl/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/syslog/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/utils-pas2js/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl-unicode/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl-console/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libxml2/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-web/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libcups/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/modplug/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libusb/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-fpcunit/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/jni/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-js/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/newt/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/ncurses/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/googleapi/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libcurl/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/iconvenc/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-process/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fpindexer/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fpmkunit/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libmagic/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/zlib/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/dts/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-report/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fppkg/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fftw/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/chm/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/sdl/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-xml/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/users/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/xforms/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/uuid/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/zorba/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/mysql/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rsvg/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/gmp/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/regexpr/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/hash/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/postgres/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/gtk2/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/opencl/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fv/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/utmp/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/sqlite/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/numlib/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/lua/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-async/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/ggi/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/unzip/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pastojs/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl-generics/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/ibase/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-stl/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libtar/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libsee/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libgd/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl-objpas/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-net/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/cdrom/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/hermes/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-base/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/gdbint/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/x11/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-registry/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/dblib/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/paszlib/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/bzip2/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/libfontconfig/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/httpd22/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-passrc/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/bfd/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/odbc/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/aspell/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/dbus/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl-extra/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fastcgi/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/")
SEARCH_DIR("/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/")
INPUT(
/usr/lib/x86_64-linux-gnu/crti.o
/usr/lib/x86_64-linux-gnu/crtbeginS.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/si_c.o
units/strumpract.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/system.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/objpas.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/cmem.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/cthreads.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/baseunix.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/classes.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/math.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/sysutils.o
units/filelistform.o
units/msegui.o
units/main.o
units/aboutform.o
units/mseact.o
units/drums.o
units/songplayer.o
units/commander.o
units/config.o
units/guitars.o
units/recorder.o
units/imagedancer.o
units/infos.o
units/status.o
units/spectrum1.o
units/waveform.o
units/randomnote.o
units/equalizer.o
units/findmessage.o
units/dialogfiles.o
units/dockpanel1.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/linux.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/unix.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/unixtype.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/initc.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/dl.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/unixutil.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/ctypes.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/types.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/typinfo.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/rtlconsts.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/errors.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/sysconst.o
units/msetypes.o
units/mseglob.o
units/mseguiglob.o
units/mseguiintf.o
units/msetimer.o
units/mseapplication.o
units/msestat.o
units/msemenus.o
units/msefileutils.o
units/msegraphics.o
units/msegraphutils.o
units/mseevent.o
units/msedatalist.o
units/mseclasses.o
units/msegridsglob.o
units/mseforms.o
units/msedock.o
units/msedragglob.o
units/msesimplewidgets.o
units/mclasses.o
units/msewidgets.o
units/msebitmap.o
units/msedataedits.o
units/msedatanodes.o
units/mseedit.o
units/msefiledialogx.o
units/msegrids.o
units/mseificomp.o
units/mseificompglob.o
units/mseifiglob.o
units/mselistbrowser.o
units/msestatfile.o
units/msestream.o
units/msestrings.o
units/msesys.o
units/msegraphedits.o
units/msescrollbar.o
units/msedispwidgets.o
units/mserichstring.o
units/msedropdownlist.o
units/mseerr.o
units/msesystypes.o
units/msesysintf.o
units/msesetlocale.o
units/cwstring.o
units/mselibc.o
units/msectypes.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/dynlibs.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/strings.o
units/msearrayutils.o
units/msereal.o
units/msesysintf1.o
units/msesysutils.o
units/mseformatstr.o
units/msedynload.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl-objpas/dateutils.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/unixcp.o
units/msethread.o
units/mselist.o
units/msekeyboard.o
units/msebits.o
units/msemacros.o
units/msearrayprops.o
units/mseinterfaces.o
units/msehash.o
units/mseeditglob.o
units/msestreaming.o
units/msedatamodules.o
units/msefloattostr.o
units/msedate.o
units/mseprocutils.o
units/msepipestream.o
units/mseprocmonitor.o
units/mse_formatfunc.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/x11/xlib.o
units/msepointer.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/x11/x.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/x11/xutil.o
units/mxft.o
units/mxrender.o
units/mxrandr.o
units/mshape.o
units/msestockobjects.o
units/msefont.o
units/mseassistiveclient.o
units/msethreadcomp.o
units/msefontconfig.o
units/msesonames.o
units/sm.o
units/ice.o
units/mseactions.o
units/msex11gdi.o
units/msesysdnd.o
units/mseprocess.o
units/msegraphicstream.o
units/msefpimage.o
units/mseshapes.o
units/mseassistiveserver.o
units/msedrawtext.o
units/msestockobjects_mfm.o
units/mseconsts.o
units/msemenuwidgets.o
units/mseinplaceedit.o
units/mseobjectpicker.o
units/msedrag.o
units/msemime.o
units/msewidgetgrid.o
units/msesumlist.o
units/msetriaglob.o
units/msefcfontselect.o
units/msepolytria.o
units/mselinetria.o
units/mseellipsetria.o
units/msenoise.o
units/msesplitter.o
units/msetabs.o
units/msetabsglob.o
units/msedialog.o
units/msedirtree.o
units/mseimage.o
units/msevaluenodesglob.o
units/mseifigui.o
units/mseifi.o
units/mseifilink.o
units/mseifidialogcomp.o
units/msebintree.o
units/msesockets.o
units/msecryptio.o
units/msesercomm.o
units/msecommport.o
units/msesocketintf.o
units/msetmpmodules.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl-objpas/variants.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl-objpas/varutils.o
units/mseobjecttext.o
units/mserttistat.o
units/msevaluenodes.o
units/msesizingform.o
units/msedirtree_mfm.o
units/msefiledialog.o
units/msefiledialog_mfm.o
units/msestringenter.o
units/msefiledialogres.o
units/msestringcontainer.o
units/msestringenter_mfm.o
units/msefiledialogres_mfm.o
units/msefiledialogx_mfm.o
units/filelistform_mfm.o
units/findmessage_mfm.o
units/uos_flat.o
units/mse_ovobasetag.o
units/mse_ovoaudiotag.o
units/mse_ovofile_mp3.o
units/uos.o
units/uos_portaudio.o
units/uos_libsndfile.o
units/uos_mpg123.o
units/uos_soundtouch.o
units/infos_mfm.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-base/contnrs.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-json/fpjson.o
units/ovosong.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl-objpas/strutils.o
units/ovofile_dummy.o
units/mse_ovotag_dummy.o
units/mse_ovotag_id3v2.o
units/ovocommonfunctions.o
units/ovoid3v1genres.o
units/mseformatbmpicoread.o
units/mseformatjpgread.o
units/mseformatpngread.o
units/songplayer_mfm.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-process/process.o
units/msechart.o
units/msetraywidget.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-process/pipes.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/termio.o
units/msedial.o
units/status_mfm.o
units/msestatusnotifieritem.o
units/msedbusinterface.o
units/msedbus.o
units/msehashstore.o
units/msestringident.o
units/mselinklist.o
units/mselfsr.o
units/main_mfm.o
units/msecolordialog.o
units/msecolordialog_mfm.o
units/config_mfm.o
units/spectrum1_mfm.o
units/msedockpanelform.o
units/dockpanel1_mfm.o
units/recorder_mfm.o
units/alsa_mixer.o
units/commander_mfm.o
units/drums_mfm.o
units/msechartedit.o
units/msesiggui.o
units/msesignal.o
units/msefft.o
units/msefftw.o
units/randomnote_mfm.o
units/guitars_mfm.o
units/waveform_mfm.o
units/equalizer_mfm.o
units/dialogfiles_mfm.o
units/bgragraphics.o
units/bgrabitmap.o
units/bgradefaultbitmap.o
units/bgrabitmaptypes.o
units/mseopenglwidget.o
units/msewindowwidget.o
units/bgraclasses.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpimage.o
units/bgrautf8.o
units/bgraunicode.o
units/bgramseguibitmap.o
units/bgramultifiletype.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/rtl/fgl.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpreadxwd.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpreadxpm.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpwritejpeg.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpwritebmp.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpwritepcx.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpwritetga.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpwritexpm.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpreadpnm.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpwritepnm.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/xwdfile.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jpeglib.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpreadjpeg.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jcapistd.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jcapimin.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdatadst.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jcparam.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jerror.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdeferr.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jmorecfg.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdapimin.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdatasrc.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdapistd.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jinclude.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jmemmgr.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdmarker.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdinput.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jcomapi.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jutils.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jmemnobs.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdmaster.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdcolor.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdsample.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdpostct.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jddctmgr.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdphuff.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdhuff.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdcoefct.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdmainct.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jquant1.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jquant2.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdmerge.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jdct.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jidctfst.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jidctint.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jidctflt.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jidctred.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jcinit.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jcmarker.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jcphuff.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jchuff.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jcmaster.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jccolor.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jcsample.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jcprepct.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jcdctmgr.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jccoefct.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jcmainct.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jfdctint.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jfdctfst.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/pasjpeg/jfdctflt.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/bmpcomn.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpimgcmn.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/pcxcomn.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/targacmn.o
units/bgratext.o
units/bgracanvas.o
units/bgracanvas2d.o
units/bgratransform.o
units/bgratextbidi.o
units/universaldrawer.o
units/bgragrayscalemask.o
units/bgrapen.o
units/bgrapath.o
units/bgrapolygon.o
units/bgrapolygonaliased.o
units/bgrablend.o
units/bgraresample.o
units/bgrafillinfo.o
units/bgragradientscanner.o
units/bgrasse.o
units/bgraarrow.o
units/bgrareadbmp.o
units/bgrareadjpeg.o
units/bgrawritepng.o
units/bgrawritetiff.o
units/bgrafilterblur.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/pngcomn.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/paszlib/zstream.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/paszlib/zbase.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/paszlib/gzio.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/hash/crc.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/paszlib/zdeflate.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/paszlib/zinflate.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/paszlib/trees.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/paszlib/adler.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/paszlib/infblock.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/paszlib/infutil.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/paszlib/infcodes.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/paszlib/inftrees.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/paszlib/inffast.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fptiffcmn.o
units/bgrafiltertype.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-base/base64.o
units/bgraunicodetext.o
units/bgrafilters.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpreadpcx.o
units/bgradithering.o
units/bgrafilterscanner.o
units/bgrapalette.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-base/avl_tree.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-base/bufstream.o
units/bgrareadbmpmiomap.o
units/bgrareadgif.o
units/bgrareadico.o
units/bgrareadlzp.o
units/bgrareadpcx.o
units/bgrareadpng.o
units/bgrareadpsd.o
units/bgrareadtga.o
units/bgrareadxpm.o
units/bgrawritelzp.o
units/bgrareadwebp.o
units/bgrawritewebp.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpreadgif.o
units/bgraiconcursor.o
units/bgrawinresource.o
units/bgracolorquantization.o
units/bgralzpcommon.o
units/bgracompressablebitmap.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpreadpsd.o
/home/fred/fpc-ootb_bin/fpc-ootb-323-x86_64-linux/units/x86_64-linux/fcl-image/fpreadtga.o
units/libwebp.o
units/linuxlib.o
units/msegl.o
units/mseglx.o
units/mseglextglob.o
units/mseglext.o
units/mseglu.o
units/imagedancer_mfm.o
units/aboutform_mfm.o
units/msefpreadjpeg.o
units/mse_jpeglib_del.o
units/mse_jdapimin_del.o
units/mse_jdatasrc_del.o
units/mse_jdapistd_del.o
units/mse_jmorecfg_del.o
units/mse_jdeferr_del.o
units/mse_jinclude_del.o
units/mse_jerror_del.o
units/mse_jmemmgr_del.o
units/mse_jdmarker_del.o
units/mse_jdinput_del.o
units/mse_jcomapi_del.o
units/mse_jutils_del.o
units/mse_jmemnobs_del.o
units/mse_jdmaster_del.o
units/mse_jdcolor_del.o
units/mse_jdsample_del.o
units/mse_jdpostct_del.o
units/mse_jddctmgr_del.o
units/mse_jdphuff_del.o
units/mse_jdhuff_del.o
units/mse_jdcoefct_del.o
units/mse_jdmainct_del.o
units/mse_jquant1_del.o
units/mse_jquant2_del.o
units/mse_jdmerge_del.o
units/mse_jdct_del.o
units/mse_jidctfst_del.o
units/mse_jidctint_del.o
units/mse_jidctflt_del.o
units/mse_jidctred_del.o
units/msefpreadpng.o
units/mse_zstream.o
units/msefpimgcmn.o
units/msepngcomn.o
)
INPUT(
-l:libc.so
-lpthread
-l:libdl.so
-l:libX11.so.6
-l:libpthread.so
-l:librt.so
-lm
)
GROUP(
-lc
)
INPUT(
/usr/lib/x86_64-linux-gnu/crtendS.o
/usr/lib/x86_64-linux-gnu/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
